-- V2__users.sql — Phase 1.1 user domain (ADR-0003, ADR-0007, ADR-0016).
--
-- The user/security spine: a local user record linked to a Google identity by
-- `sub`, with locally-managed roles and an `enabled` flag. Conventions follow
-- V1/ADR-0016 (bigint identity PK, app-side audit timestamps, no DB triggers).

create table app_user (
    id         bigint generated by default as identity primary key,
    -- Google subject claim: null until claimed at first Google login (ADR-0007),
    -- unique when set (partial index below — a plain UNIQUE would forbid more
    -- than one null seed row).
    sub        varchar(255),
    -- email is the login identifier for the form-stub and is set once (ADR-0007).
    email      varchar(255) not null,
    name       varchar(255) not null,
    enabled    boolean      not null default true,
    created_at timestamptz  not null,
    updated_at timestamptz  not null,
    constraint uq_app_user_email unique (email)
);

create unique index uq_app_user_sub on app_user (sub) where sub is not null;

-- Locally-managed roles as an @ElementCollection (ADR-0007). Subsumption is NOT
-- stored: an admin row holds only 'ADMIN' and gains 'USER' at runtime via the
-- RoleHierarchy bean (ADR-0008).
create table user_roles (
    user_id bigint      not null references app_user (id) on delete cascade,
    role    varchar(20) not null,
    primary key (user_id, role)
);

-- Bootstrap admin (ADR-0007): the pre-seeded ADMIN so admin screens aren't
-- locked out on a fresh DB. `sub` is null — Google assigns it at first login,
-- when provisioning "claims" this row by email (Phase 1.2). The identity is
-- resolved from the app.admin.email property via a Flyway placeholder, so each
-- profile seeds its own admin (jean-christophe@vaadin.com in local).
insert into app_user (email, name, enabled, created_at, updated_at)
values ('${adminEmail}', 'Expense Admin', true, now(), now());

insert into user_roles (user_id, role)
select id, 'ADMIN' from app_user where email = '${adminEmail}';
