-- V3__reference_data.sql — Phase 2.1 reference data (ADR-0018, ADR-0010, ADR-0016).
--
-- Two admin-editable reference tables the expense lines (Phase 2.3) are filed
-- against: VAT rates and expense types. Conventions follow V1/ADR-0016 (bigint
-- identity PK, app-side audit timestamps set by Hibernate — no DB triggers).
--
-- Seed values are the Finnish (Verohallinto) 2026 figures (F-003): general
-- 25.5 %, reduced 13.5 % (14 % → 13.5 % on 1 Jan 2026), reduced 10 %, and 0 %.
-- Verify against the Verohallinto decision for the target year before shipping a
-- rate change — do NOT edit an in-use rate's value; deactivate it and add the
-- new one so filed lines keep their original rate (ADR-0018).

create table vat_rate (
    id            bigint        generated by default as identity primary key,
    -- Percent, e.g. 25.50. numeric(5,2) is percent precision (ADR-0010), not the
    -- money numeric(19,2); scale 2 covers rates like 13.50.
    value         numeric(5, 2) not null,
    display_order integer       not null,
    active        boolean       not null default true,
    created_at    timestamptz   not null,
    updated_at    timestamptz   not null
);

create table expense_type (
    id                  bigint       generated by default as identity primary key,
    name                varchar(255) not null,
    display_order       integer      not null,
    active              boolean      not null default true,
    -- Required default rate a new line pre-fills (ADR-0018): NOT NULL FK.
    default_vat_rate_id bigint       not null references vat_rate (id),
    created_at          timestamptz  not null,
    updated_at          timestamptz  not null
);

create index idx_expense_type_default_vat_rate on expense_type (default_vat_rate_id);

-- Seed the 2026 VAT rates in display order (F-003).
insert into vat_rate (value, display_order, active, created_at, updated_at) values
    (25.5, 0, true, now(), now()),
    (13.5, 1, true, now(), now()),
    (10.0, 2, true, now(), now()),
    (0.0,  3, true, now(), now());

-- Seed the expense types, each mapped to its default rate by value (ADR-0018).
-- The seed values are distinct, so matching on value is unambiguous here.
insert into expense_type (name, display_order, active, default_vat_rate_id, created_at, updated_at)
select seed.name, seed.ord, true,
       (select id from vat_rate where value = seed.rate),
       now(), now()
from (values
    ('Travel allowance',        0, 0.0),
    ('Taxi/transport',          1, 13.5),
    ('Accommodation',           2, 13.5),
    ('Restaurant/meals',        3, 13.5),
    ('Parking/supplies/goods',  4, 25.5),
    ('Publications',            5, 10.0)
) as seed (name, ord, rate);
