-- V4__reports.sql — Phase 2.2 report save-model spine (ADR-0006, ADR-0011,
-- ADR-0016, ADR-0019).
--
-- The ExpenseReport aggregate root and its ordered StatusChange log. Lines
-- (ExpenseLine) and the money columns they carry arrive in a later phase (2.3);
-- until then a report's total is derived as €0.00 and nothing here stores an
-- amount. Conventions follow V1/ADR-0016: bigint identity PKs, app-side audit
-- timestamps set by Hibernate (no DB triggers).

create table expense_report (
    id                     bigint       generated by default as identity primary key,
    -- Optimistic-lock version (ADR-0011): the aggregate root carries it; a stale
    -- whole-aggregate write throws OptimisticLockException. Starts at 0.
    version                bigint       not null,
    -- The owning user (ADR-0006): exactly one owner, set at creation, never
    -- reassigned. NOT NULL FK; My Reports and every read is owner-scoped on it.
    owner_id               bigint       not null references app_user (id),
    -- User-entered report date, defaulting to today in the UI (distinct from the
    -- audit created_at). The natural sort key and primary label in My Reports.
    report_date            date         not null,
    -- Optional free-text note; no title field exists by design (glossary).
    additional_information text,
    -- Lifecycle status (ADR-0006): starts DRAFT. Stored as the enum name.
    status                 varchar(20)  not null,
    created_at             timestamptz  not null,
    updated_at             timestamptz  not null
);

create index idx_expense_report_owner on expense_report (owner_id);

-- Ordered status-change log owned by the aggregate (glossary: Status Change).
-- Modelled now; entries are appended from Phase 2.4 onward (submit/approve/
-- reject). entry_index preserves insertion order for the @OrderColumn mapping.
create table status_change (
    id             bigint       generated by default as identity primary key,
    report_id      bigint       not null references expense_report (id) on delete cascade,
    entry_index    integer      not null,
    from_status    varchar(20)  not null,
    to_status      varchar(20)  not null,
    -- The user who performed the transition (owner on submit/resubmit, admin on
    -- approve/reject). NOT NULL FK.
    acting_user_id bigint       not null references app_user (id),
    -- Optional note; mandatory on reject from Phase 5.
    comment        text,
    changed_at     timestamptz  not null,
    constraint uq_status_change_order unique (report_id, entry_index)
);

create index idx_status_change_report on status_change (report_id);
