-- V5__expense_lines.sql — Phase 2.3 expense lines (ADR-0006, ADR-0010,
-- ADR-0016, ADR-0018, ADR-0019).
--
-- The ExpenseLine collection owned by the ExpenseReport aggregate. Each line
-- carries a required expense type + VAT rate (references into the Phase 2.1
-- reference tables; the rate defaults from the type but is overridable) and a
-- gross, non-zero amount as numeric(19,2) money (ADR-0010). Net/VAT and the
-- report total are derived, never stored. Conventions follow V4/ADR-0016:
-- bigint identity PK, app-side audit timestamps set by Hibernate.

create table expense_line (
    id              bigint        generated by default as identity primary key,
    -- Owning report; the aggregate maps this FK and the line_index order column.
    report_id       bigint        not null references expense_report (id) on delete cascade,
    -- Insertion order within the report (@OrderColumn). Contiguous 0..n-1.
    line_index      integer       not null,
    -- Classification + VAT rate (ADR-0018). Referenced, never copied: a rate the
    -- admin later deactivates is retained, so a historical line keeps its rate.
    expense_type_id bigint        not null references expense_type (id),
    vat_rate_id     bigint        not null references vat_rate (id),
    -- Gross amount as entered (what the user paid). Required and non-zero
    -- (negatives allowed for credits/corrections — enforced in the domain).
    amount          numeric(19, 2) not null,
    -- Optional free-text note; no business date and no description by design.
    comment         text,
    created_at      timestamptz   not null,
    updated_at      timestamptz   not null,
    -- Insertion order is unique per report. DEFERRABLE INITIALLY DEFERRED so a
    -- whole-aggregate save that reorders/recompacts line_index (e.g. a middle
    -- line removed, orphan-removal shifts the rest) is validated only at commit,
    -- once the indices are contiguous again — Hibernate rewrites them row by row.
    constraint uq_expense_line_order unique (report_id, line_index)
        deferrable initially deferred
);

create index idx_expense_line_report on expense_line (report_id);
create index idx_expense_line_expense_type on expense_line (expense_type_id);
create index idx_expense_line_vat_rate on expense_line (vat_rate_id);
