-- V5__expense_lines.sql — Phase 2.3 report lines (ADR-0006, ADR-0010,
-- ADR-0018, ADR-0019).
--
-- The ExpenseLine child of the ExpenseReport aggregate (ADR-0006): a report is
-- built line by line and saved whole. Each line is filed against a required
-- expense type and VAT rate (the Phase 2.1 reference tables) and carries the
-- gross amount the user paid; net and VAT are always derived, never stored
-- (ADR-0010). Conventions follow V1/V4 (bigint identity PK, app-side audit
-- timestamps set by Hibernate — no DB triggers).

create table expense_line (
    id              bigint        generated by default as identity primary key,
    -- Owning aggregate; cascade-deleted with the report. The report collection
    -- maps this FK and the line_index order column (owning side), matching the
    -- status_change mapping in V4.
    report_id       bigint        not null references expense_report (id) on delete cascade,
    -- Insertion order within the report, populated by the @OrderColumn mapping.
    line_index      integer       not null,
    -- Required classification (ADR-0018). A now-deactivated type stays referenced
    -- here so a historical line keeps it — deactivation only hides it from new
    -- lines; the row is never deleted.
    expense_type_id bigint        not null references expense_type (id),
    -- Required VAT rate, defaulted from the type but overridable (ADR-0018). As
    -- with the type, a deactivated rate remains referenced by filed lines.
    vat_rate_id     bigint        not null references vat_rate (id),
    -- Gross amount the user paid, EUR numeric(19,2) (ADR-0010). Non-zero
    -- (negatives allowed for credits/corrections) — the aggregate owns that
    -- guard; the DB check is a belt-and-suspenders backstop.
    amount          numeric(19, 2) not null,
    comment         text,
    created_at      timestamptz   not null,
    updated_at      timestamptz   not null,
    -- Order uniqueness is DEFERRABLE: a whole-aggregate save reconciles the line
    -- collection (insert/update/orphan-remove) and Hibernate rewrites line_index
    -- values within the transaction, transiently colliding before it settles.
    -- Postgres checks a deferred constraint at commit, by which point the indices
    -- are contiguous again; an immediate check would fail mid-statement.
    constraint uq_expense_line_order unique (report_id, line_index)
        deferrable initially deferred,
    constraint ck_expense_line_amount_nonzero check (amount <> 0)
);

create index idx_expense_line_report on expense_line (report_id);
create index idx_expense_line_expense_type on expense_line (expense_type_id);
create index idx_expense_line_vat_rate on expense_line (vat_rate_id);
