-- V6__receipts.sql — Phase 3.1 receipts write path (ADR-0009, ADR-0021,
-- ADR-0016).
--
-- A receipt is a scanned document (JPEG/PNG/PDF, ≤ 10 MB) attached to one
-- expense line: 0..1 per line, always optional (glossary: Receipt). It lives in
-- its own table — physically separate from the hot expense_line row — so the
-- bytea blob never rides a line/report load (ADR-0021). The relationship is a
-- unidirectional one-to-one OWNED BY THE RECEIPT: the FK and its uniqueness sit
-- here, and ExpenseLine carries no reference back, which makes "blobs never ride
-- a hot query" structural rather than dependent on a lazy-fetch annotation.
--
-- The content_type stored is the server-side SNIFFED signature (magic bytes),
-- never the browser's claim (ADR-0021). Conventions follow V4/V5/ADR-0016:
-- bigint identity PK, app-side audit timestamps set by Hibernate.

create table receipt (
    id              bigint        generated by default as identity primary key,
    -- The owning expense line. UNIQUE enforces the 0..1-per-line cardinality;
    -- ON DELETE CASCADE removes the receipt when its line is orphan-removed or
    -- the whole report is deleted (the line side has no ORM back-reference, so
    -- the database owns that cleanup).
    expense_line_id bigint        not null unique
                        references expense_line (id) on delete cascade,
    -- The sniffed MIME type (image/jpeg, image/png, application/pdf). NOT NULL:
    -- a receipt with no verified type is never stored.
    content_type    varchar(100)  not null,
    -- Original client-supplied filename, for display and Content-Disposition on
    -- the (out-of-scope) read path. Optional.
    filename        varchar(255),
    -- Byte length of the stored blob, for display without loading the bytea.
    size_bytes      bigint        not null,
    -- The file bytes. Kept off every summary/aggregate query — read only by the
    -- dedicated download projection on the read-path slice (ADR-0021).
    data            bytea         not null,
    created_at      timestamptz   not null,
    updated_at      timestamptz   not null
);
