-- V7__allowance_rates.sql — Phase 4.1 allowance rate config (PRD 4.1/4.4,
-- ADR-0003, ADR-0010, ADR-0016).
--
-- The per-year reference data the Travel Calculator (Phase 4.2/4.3) costs
-- against: domestic per-diem, kilometre rate, meal allowance (ateriakorvaus),
-- and foreign per-diem by country. Conventions follow V1/ADR-0016 (bigint
-- identity PK, app-side audit timestamps set by Hibernate — no DB triggers).
--
-- HISTORY BY YEAR, NOT BY active FLAG. Deliberately unlike the VAT/expense-type
-- reference tables (V3, ADR-0018), which keep history via an `active` flag: an
-- allowance rate is keyed by `year`, so each year's decision is its own row and
-- prior years are never mutated when a new year is added. The Verohallinto
-- publishes a fresh decision per year; modelling by year mirrors that.
--
-- PROVISIONAL 2026 VALUES — VERIFY AGAINST THE VEROHALLINTO DECISION BEFORE
-- SHIPPING. The domestic/km/meal figures below are the PRD's provisional 2026
-- numbers (full EUR 54 / partial EUR 25 / meal EUR 13.50 / km EUR 0.59,
-- thresholds 10 h / 6 h). The foreign per-diem starter set is a representative
-- ~12-country sample at plausible amounts, NOT the confirmed 2026 table. An
-- admin corrects any figure at runtime via the Allowance rates settings screen
-- (Phase 4.4); see docs/findings.md F-032.

-- Domestic per-diem: one row per year (PRD 4.1). Amounts are money
-- (numeric(19,2), ADR-0010); thresholds are whole hours.
create table domestic_per_diem_rate (
    id                    bigint        generated by default as identity primary key,
    year                  integer       not null unique,
    full_day_amount       numeric(19, 2) not null,
    partial_day_amount    numeric(19, 2) not null,
    -- A trip qualifies for the full per-diem over this many hours, the partial
    -- over the lower threshold (partial < full).
    full_day_min_hours    integer       not null,
    partial_day_min_hours integer       not null,
    created_at            timestamptz   not null,
    updated_at            timestamptz   not null
);

-- Kilometre compensation: one €/km rate per year. A per-km rate carries
-- sub-cent precision (numeric(6,3)), unlike the money amounts.
create table kilometre_rate (
    id            bigint        generated by default as identity primary key,
    year          integer       not null unique,
    amount_per_km numeric(6, 3) not null,
    created_at    timestamptz   not null,
    updated_at    timestamptz   not null
);

-- Meal allowance (ateriakorvaus): one amount per year.
create table meal_allowance_rate (
    id         bigint        generated by default as identity primary key,
    year       integer       not null unique,
    amount     numeric(19, 2) not null,
    created_at timestamptz   not null,
    updated_at timestamptz   not null
);

-- Foreign per-diem: an amount per (year, country). Country is the free-text
-- country name; unique within a year.
create table foreign_per_diem_rate (
    id         bigint        generated by default as identity primary key,
    year       integer       not null,
    country    varchar(255)  not null,
    amount     numeric(19, 2) not null,
    created_at timestamptz   not null,
    updated_at timestamptz   not null,
    constraint uq_foreign_per_diem_year_country unique (year, country)
);

create index idx_foreign_per_diem_year on foreign_per_diem_rate (year);

-- Seed the provisional 2026 values (verify against Verohallinto — see header).
insert into domestic_per_diem_rate
    (year, full_day_amount, partial_day_amount, full_day_min_hours, partial_day_min_hours, created_at, updated_at)
values
    (2026, 54.00, 25.00, 10, 6, now(), now());

insert into kilometre_rate (year, amount_per_km, created_at, updated_at)
values (2026, 0.590, now(), now());

insert into meal_allowance_rate (year, amount, created_at, updated_at)
values (2026, 13.50, now(), now());

-- Foreign per-diem 2026 starter set (~12 countries, provisional amounts).
insert into foreign_per_diem_rate (year, country, amount, created_at, updated_at)
values
    (2026, 'Belgium',        69.00, now(), now()),
    (2026, 'Denmark',        74.00, now(), now()),
    (2026, 'Estonia',        65.00, now(), now()),
    (2026, 'France',         74.00, now(), now()),
    (2026, 'Germany',        71.00, now(), now()),
    (2026, 'Italy',          72.00, now(), now()),
    (2026, 'Netherlands',    74.00, now(), now()),
    (2026, 'Norway',         80.00, now(), now()),
    (2026, 'Spain',          70.00, now(), now()),
    (2026, 'Sweden',         68.00, now(), now()),
    (2026, 'United Kingdom', 82.00, now(), now()),
    (2026, 'United States',  76.00, now(), now());
