-- V8__travel.sql — Phase 4.2/4.3 Travel Calculator (ADR-0006, ADR-0010,
-- ADR-0016, ADR-0019).
--
-- A trip on a report (glossary: Travel Calculator). The Travel holds the trip
-- INPUTS only (dates/times, destinations, purpose, country, flags) — no money.
-- The per-diem it earns lives on a GENERATED expense_line linked back to it via
-- the new expense_line.travel_id FK; a line with a travel_id is generated
-- (read-only), a null one is manual. Conventions follow V4/V5/ADR-0016: bigint
-- identity PK, app-side audit timestamps set by Hibernate, an @OrderColumn owned
-- by the aggregate with a deferrable uniqueness constraint.

create table travel (
    id                         bigint      generated by default as identity primary key,
    -- Owning report; the aggregate maps this FK and the travel_index order column.
    report_id                  bigint      not null references expense_report (id) on delete cascade,
    -- Insertion order within the report (@OrderColumn). Contiguous 0..n-1.
    travel_index               integer     not null,
    -- Trip inputs. Dates are LocalDateTime (no zone) — a trip's wall-clock times.
    departure_at               timestamp   not null,
    return_at                  timestamp   not null,
    destinations               varchar(255) not null,
    purpose                    varchar(255) not null,
    -- Domestic trips are Finland; the foreign country picker is Slice 4.
    country                    varchar(255) not null,
    not_eligible_for_allowance boolean     not null default false,
    free_lunch                 boolean     not null default false,
    charge_to_customer         boolean     not null default false,
    created_at                 timestamptz not null,
    updated_at                 timestamptz not null,
    constraint uq_travel_order unique (report_id, travel_index)
        deferrable initially deferred
);

create index idx_travel_report on travel (report_id);

-- Link a generated per-diem line to the trip that produced it. Nullable: a null
-- travel_id is a manual line. ON DELETE CASCADE so removing a trip (or its whole
-- report) takes its generated line with it — the aggregate already orphan-removes
-- it, this is the DB-level safety net.
alter table expense_line
    add column travel_id bigint references travel (id) on delete cascade;

create index idx_expense_line_travel on expense_line (travel_id);
